.SILENT: ;               # no need for @
.ONESHELL: ;             # recipes execute in same shell
.NOTPARALLEL: ;          # wait for this target to finish
.EXPORT_ALL_VARIABLES: ; # send all vars to shell
Makefile: ;              # skip prerequisite discovery

SHELL ?= /bin/bash

# Determine this Makefile as Main file
THIS_MAKEFILE := $(word $(words $(MAKEFILE_LIST)), $(MAKEFILE_LIST))

# =================================================================
include ./.makefiles/colors.mk
include ./.makefiles/logo.mk
include ./.makefiles/functions.mk
# =================================================================

.PHONY: fullclean help

# Run make help by default
.DEFAULT_GOAL = help

# =================================================================
# Definitions:
# =================================================================

# Current Working Dir (Full path)
CWD        := $(shell cd $(shell dirname $(THIS_MAKEFILE)); pwd)
# Filter Makefile Input params to use they as target input params
ARGS       := $(filter-out $@, $(MAKECMDGOALS))
# Define Zephir SRC, bin, extension, etc...
ZEPHIR_SRC := $(call config,ZEPHIR_SRC,$(CWD)/.env)
ZEPHIR_BIN := $(ZEPHIR_SRC)/zephir
ZEPHIR_EXT := $(ZEPHIR_SRC)/ext/modules/test.so

ZEPHIR_VND := $(ZEPHIR_SRC)/vendor/bin

PHPUNIT     := $(ZEPHIR_VND)/simple-phpunit
PHPUNIT_EXT := php -d extension=$(ZEPHIR_EXT) $(PHPUNIT)
TEST_OPTS   := --configuration $(ZEPHIR_SRC)/phpunit.xml.dist

FILTER  = $(if $(filter-out $@, $(ARGS)), --filter $(filter-out $@, $(ARGS)), "")

# =================================================================
# Makefile Targets:
# =================================================================

---: ## --------------------------------------------------------------
fullclean: ## Cleans any object files created by the extension (incl. files generated by phpize)
	$(ZEPHIR_BIN) fullclean

---: ## --------------------------------------------------------------
test-kernel: ## Run Zephir Kernel Tests
	cd $(ZEPHIR_SRC) && $(PHPUNIT_EXT) $(TEST_OPTS) $(FILTER) --testsuite Zephir

---: ## --------------------------------------------------------------
help: .logo ## Show this help and exit
	@echo "$(Yellow)Usage:$(NC)\n  make [command] [arguments]"
	@echo ''
	@echo "$(Yellow)Arguments:$(NC)"
	printf "  $(Green)%-15s$(NC) %s\n" "testName" "for all test runners - Filter which tests to run"
	@echo ''
	@echo "$(Yellow)Targets:$(NC)"
	@echo ''
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(THIS_MAKEFILE) | awk 'BEGIN {FS = ":.*?## "}; \
		{printf "  $(Cyan)%-15s$(NC) %s\n", $$1, $$2}'
	@echo ''
%:
	@:
